[Icon Theme]
Name=sielo-default
Comment=The Sielo default theme
Directories=images/edit,images/other,images/preferences,images/tabs

[images/edit]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128

[images/other]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128


[images/preferences]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128


[images/tabs]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128
