[Icon Theme]
Name=dark
Comment=Theme by Dark
Directories=edit,other,preferences,tabs,titlebar

[edit]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128

[other]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128


[preferences]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128


[tabs]
Size=128
Context=Apps
Type=Scalable
MinSize=16
MaxSize=128

[titlebar]
Size=10
Context=Apps
Type=Scalable
MinSize=10
MaxSize=128
